;; close tool bar
(tool-bar-mode -1)

;; close menu bar
(menu-bar-mode -1)

;; close scroll bar
(scroll-bar-mode -1)

;; disable line highline
(global-hl-line-mode -1)

;; 使用边缘填充
(fringe-mode 0)

;; 不在 modeline 显示时间
(display-time-mode -1)

;; show line number
(global-linum-mode 1)

;; 某些 mode 关闭行号
(use-package linum-off
  :config
  (setq linum-disabled-modes-list
        '(eshell-mode
          wl-summary-mode
          compilation-mode
          org-mode
          text-mode
          dired-mode
          nov-mode
          pdf-view-mode)))

;; change the style of cursor
(setq cursor-type 'bar)

;; close help page at startup
(setq inhibit-splash-screen 1)


(setq-default truncate-lines nil)
(setq-default truncate-partial-width-windows nil)

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-ADBO-Source Code Pro-ultrabold-italic-normal-*-*-*-*-*-m-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 26.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset            
   (font-spec :name "-ADBE-Source Han Sans CN Medium-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 31.5)))



;; 启动最大化窗口
(setq  initial-frame-alist (quote ((fullscreen . maximized))))


(use-package all-the-icons)



(use-package doom-themes
  :config
  (setq doom-themes-enable-bold t)    ; if nil, bold is universally disabled
  (setq doom-themes-enable-italic t)  ; if nil, italics is universally disabled
  (setq doom-modeline-buffer-file-name-style 'buffer-name)
  
  (load-theme 'doom-solarized-light t)
  ;; (load-theme 'doom-one t)
  

  ;; Enable flashing mode-line on errors
  ;; (doom-themes-visual-bell-config)
  )


;; (use-package doom-modeline
;;   :ensure t
;;   :hook (after-init . doom-modeline-mode)
;;   :config
;;   ;; 调整 modeline 高度
;;   (setq doom-modeline-height 10)
;;   (set-face-attribute 'mode-line nil :family "Noto Sans" :height 240)
;;   (set-face-attribute 'mode-line-inactive nil :family "Noto Sans" :height 240)
;;   )

(use-package mini-modeline
  ;; :after
  ;; smart-mode-line
  :config
  (setq mini-modeline-display-gui-line t)
  (mini-modeline-mode t))

;; (use-package olivetti
;;   :init
;;   (setq olivetti-body-width 90)
;;   :hook
;;   (olivetti-mode . toggle-word-wrap)
;; 
;;   )

(use-package writeroom
  :bind
  ("C-c w" . writeroom-mode)
  )

;; (use-package page-break-lines)
;; 
;; (use-package dashboard
;;   :preface
;;   (defun my/dashboard-banner ()
;;     "Set a dashboard banner including information on package initialization
;;   time and garbage collections."""
;;     (setq dashboard-banner-logo-title
;;           (format "Emacs ready in %.2f seconds with %d garbage collections."
;;                   (float-time (time-subtract after-init-time before-init-time)) gcs-done)))
;;   :config
;;   (setq dashboard-center-content t)
;;   
;;   (setq dashboard-startup-banner 'logo)
;;   (dashboard-setup-startup-hook)
;;   
;;   :hook ((after-init     . dashboard-refresh-buffer)
;;          (dashboard-mode . my/dashboard-banner)
;;          (dashboard-mode . turn-on-page-break-lines-mode)))


;; 在 org-mode 中疑似有性能问题
;; (use-package indent-guide
;;   :ensure t
;;   :config
;;   (add-hook 'prog-mode-hook 'indent-guide-mode)
;;   (add-hook 'org-mode-hook 'indent-guide-mode)
;;   (setq indent-guide-delay 0)
;;   (setq indent-guide-recursive nil)
;;   (setq indent-guide-char "|"))

(use-package awesome-tab
  :commands (awesome-tab-mode)
  :load-path "site-lisp/awesome-tab"
  :init
  (defhydra hydra-tab (
                       :pre (awesome-tab-mode t)
                       :post (awesome-tab-mode -1))
    "
 ^^^^Fast Move             ^^^^Tab                    ^^Search            ^^Misc
-^^^^--------------------+-^^^^---------------------+-^^----------------+-^^---------------------------
   ^_k_^   prev group    | _C-a_^^     select first | _b_ search buffer | _C-k_   kill buffer
 _h_   _l_  switch tab   | _C-e_^^     select last  | _g_ search group  | _C-S-k_ kill others in group
   ^_j_^   next group    | _a_^^     ace jump       | ^^                | ^^
 ^^0 ~ 9^^ select window | _C-h_/_C-l_ move current | ^^                | ^^
-^^^^--------------------+-^^^^---------------------+-^^----------------+-^^---------------------------
"
    ("h" awesome-tab-backward-tab)
    ("j" awesome-tab-forward-group)
    ("k" awesome-tab-backward-group)
    ("l" awesome-tab-forward-tab)
    ("a" awesome-tab-ace-jump)
    ("C-a" awesome-tab-select-beg-tab)
    ("C-e" awesome-tab-select-end-tab)
    ("C-h" awesome-tab-move-current-tab-to-left)
    ("C-l" awesome-tab-move-current-tab-to-right)
    ("b" ivy-switch-buffer)
    ("g" awesome-tab-counsel-switch-group)
    ("C-k" kill-current-buffer)
    ("C-S-k" awesome-tab-kill-other-buffers-in-current-group)
    ("q" nil "quit"))
  :bind
  (("M-t" . hydra-tab/body))
  )

(provide 'init-ui)
